server:
  port: 9350

elasticsearch:
  thread: 50
  username: fastcatx
  password: fastcatx
  connectionTimeout: 30000
  socketTimeout: 300000
  nodes:
    - host: localhost
      port: 9200
      scheme: http
    - host: localhost
      port: 9200
      scheme: http
