server:
  port: 9350
logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.danawa.fastcatx: INFO
  file:
    name: output.log

elasticsearch:
  thread: 50
  username: fastcatx
  password: fastcatx
  connectionTimeout: 30000
  socketTimeout: 300000
  nodes:
    - host: es2.danawa.com
      port: 9200
      scheme: http
    - host: es2.danawa.com
      port: 9200
      scheme: http
